config/routes.rb
Rails.application.routes.draw do
	resources :addresses
	resources :prices
	resources :events
	resources :companies
	resources :addresses

	devise_for :users, :controllers => { 
		:invitations => 'users/invitations'
	}

	resources :users, only: [:index, :destroy] 
	
	get "/users/:id/inviteUser" => "users#invite_User", :as => :invite_User

	resources :events, only: [:create] do
		get :subscribe
	end

	resources :events, only: [:destroy] do
		get :unsubscribe
	end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "events#index"
end

app/models/event.rb
class Event < ApplicationRecord
  scope :past_events, -> time {where("dt_end < ?", time).order("dt_end ASC")}
  scope :search_name, -> name {where("name like ?", )}
  #relaçoes
  belongs_to :category
  belongs_to :company
  has_many :prices, dependent: :delete_all
  belongs_to :address, dependent: :destroy

    #relação cliente => evento
    has_many :subscribes, dependent: :delete_all
    has_many :users, through: :subscribes 

  #validaçoes
  validates :title, presence:true, length: { in: 2..50 }
  validates :description, presence:true 
  validates :dt_start, presence:true
  validates :dt_end, presence:true, :if => :dt_event?

  #imagem uploader
  mount_uploader :image, ImageUploader

  def dt_event?
    if dt_end.nil? && dt_start.nil?
      dt_end >= dt_start 
    end
  end

  def self.near_search(query)
    address.near(query)
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_categories
  before_action :set_price

  # GET /events
  # GET /events.json
  def index

    if params[:time] == "Today"
      @events = Event.where(dt_start.local == Time.zone.today)

      binding.pry
    else
      @events = Event.all

    end
    @carouselEvents = Event.all.limit(3)
  end

  # GET /events/1
  # GET /events/1.json
  def show
    #binding.pry
    @prices = Price.where(event_id: @event.id)
    allEventsAddress = Address.closest_by_event(@event.address_id)
    nearAddresses = allEventsAddress.near(@event.address.street)
    @nearEvents = Event.where(address_id: nearAddresses.to_a.pluck(:id)).all.limit(3)
  end

  # GET /events/new
  def new
    @event = Event.new
    @address = Address.new
    @categories = Category.all
  end

  # GET /events/1/edit
  def edit
    @categories = Category.all
    @address = Event.find(params[:id]).address
  end

  # POST /events
  # POST /events.json
  def create

    @address = Address.new(address_params)
    @event = Event.new(event_params)
    @event.company_id = current_user.company_id

    respond_to do |format|
      if @address.save
        @event.address_id = @address.id
        if @event.save
          format.html { redirect_to edit_event_path(@event), notice: 'Event was successfully created.' }
          format.json { render :edit, status: :created, location: @event }
        else
          format.html { render :new }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }  
      end
    end
  end
  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        if @event.address.update(address_params)
          format.html { redirect_to @event, notice: 'Event was successfully updated.' }
          format.json { render :show, status: :ok, location: @event }
        else
          format.html { render :edit }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
        
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def subscribe
    Subscribe.create(user_id: current_user.id, event_id: params[:event_id])
    respond_to do |format|
      format.html { redirect_to Event.find(params[:event_id]), notice: 'Subscribed in the event.' }
      format.json { head :no_content }
    end
  end

  def unsubscribe
    Subscribe.destroy(Subscribe.where(user_id: current_user.id, event_id: params[:event_id]).ids)
    respond_to do |format|
      format.html { redirect_to Event.find(params[:event_id]), notice: 'Unsubscribed in the event.' }
      format.json { head :no_content }
    end
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def set_price
      @price = Price.find_by_event_id(params[:id]) || Price.new
    end
    
    def set_categories
      @categories = Category.all
    end

    def address_params
      params.require(:address).permit(:street, :city, :zip, :state, :latitude, :longitude)
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :contact, :dt_start, :dt_end, :category_id, 
        :company_id, :image, :time, address: [:street, :city, :zip, :state, :latitude, :longitude])
    end
  end

app/helpers/events_helper.rb
module EventsHelper


end

app/views/events/_form.html.erb
<%= form_for(@event, html: { class: "form-horizontal", role: "form" }) do |f| %>
<% if @event.errors.any? %>

<div class="alert alert-danger alert-dismissable" role="alert">
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  <h4><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h4>

  <ul>
    <% @event.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="col-md-4">
  <div class="form-group">
    <div class="col-md-12">
    <%= f.label :title, class: "text-left label-certa" %>*
      <%= f.text_field :title, class: "form-control", required: true, placeholder: "Event's Title" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-12">
    <%= f.label :contact, class: "text-left label-certa" %>*

      <%= f.text_field :contact, class: "form-control", :data => {:mask => "(00)0000-0000"}, placeholder: "(00)0000-0000" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-12">
    <%= f.label :category, class: "text-left label-certa" %>*
      <%= f.collection_select :category_id, @categories, :id, :name, {}, class: "form-control", required: true%>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-12">
    <%= f.label :description, class: "text-left label-certa"%>*
    <%= f.text_area :description, class: "form-control", 
    required: true, :rows => "10" , placeholder: "Event's description" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-12">
    <%= f.label :dt_start, class: "text-left label-certa" %>
      <div class='input-group date' id='datetimepicker1'>
        <%= f.text_field :dt_start, class: "form-control" %>
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-calendar"></span>
        </span>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-12">
    <%= f.label :dt_end, class: "text-left label-certa" %>
      <div class='input-group date' id='datetimepicker2'>
        <%= f.text_field :dt_end, class: "form-control" %>
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-calendar"></span>
        </span>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-12">
    <%= f.label "Image", class: "text-left label-certa" %>
      <%= f.file_field :image, onchange: "readURL(this)"%>
    </div>
  </div>

  <%= render :partial => "addresses/form"%>
  <br/>
  
</div>

<div class="col-md-8">
  <div class="thumbnail">
    <%= image_tag(@event.image_url.to_s, id: "img_prev", class:"img-responsive", onerror: "this.scr='public/uploads/event/image/default.png'") %>
  </div>

<% if !@event.id.blank?%>
<%= render :partial => "prices/index", locals: { prices: @event.prices} %>
<% end %>
<!--
  <div>
    <%= f.submit class: "btn btn-success btn-block", :name => "btnconfirm" %>
  </div>-->
  <% end %>
</div>

app/views/events/_list_events.html.erb
<!--
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Imagem </th>
        <th>Title</th>
        <th>Descripiton</th>
        <th>Contact</th>
        <th>dt_start</th>
        <th>dt_end</th>
        <th>category</th>
        <th>Show</th>
        <th>Edit</th>
        <th>Destroy</th>
      </tr>
    </thead>

    <tbody>
      <% events.each do |event| %>
      <tr>
        <td><%= image_tag(event.image_url(:thumb).to_s) %>%></td>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.contact %></td>
        <td><%= event.dt_start %></td>
        <td><%= event.dt_end %></td>
        <td><%= event.category %></td>
        <td><%= link_to 'Show', event, :class => 'btn btn-default' %></td>
        <td><%= link_to 'Edit', edit_event_path(event), :class => 'btn btn-default' %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>
-->

<% if events.empty? %>

<div class="alert alert-warning" role="alert">You dont have any events, please subscribe in one.</div>
<% else %>
<% events.each do |event| %>
<% case event.category.id when 1 %>
<div class="music well">
<% when 2 %>
<div class="theater well">
<% when 3 %>
<div class="cinema well">
<% when 4 %>
<div class="gastronomy well">
<% when 5 %>
<div class="architecture well">
<% when 6 %>
<div class="dance well">
<% when 7 %>
<div class="visual well">
<% when 8 %>
<div class="education well">
<% when 9 %>
<div class="congress well">
<% else %>
<div class="well">  
<% end %>



<div class="row">
  <div class="col-md-4">
    <%= image_tag(event.image, :class => "img-thumbnail img-responsive") %>
  </div>
<div class="col-md-6">
  <h2><b><%= event.title%></b></h2>
  <i><%= event.address.street%></i>

<br/><br/><br/><br/>

      <h4 class="pull-right">Category: <%= event.category.name%></h4>
  <dd><b>Premium:</b>R$ 30,00</dd>
  <dd><b>Comum:</b>R$ 15,00</dd>
</div>
<div clas="col-md-2 pull-right">

      Data start:
      <br/>
      <%= event.dt_start.strftime("%a, %d of %b %R")%>
      <br/>

      Data end:
<br/>
      <%= event.dt_end.strftime("%a, %d of %b %R")%>

  <br/>
  <br/>     <br/><br/>
      <%= link_to 'See details', event, class: 'btn btn-primary btn-lg' %>
</div>
</div>
</div>
<% end %>
<% end %>

app/views/events/_list_events_manage.html.erb
	

	<% if events.empty? %>

	<div class="alert alert-warning" role="alert">You dont have any events, please create one.</div>
	<% else %>

	<div class="row">

		<div class="text-center col-md-2">
		<b>Image</b>
		</div>
		<div class="text-center col-md-2">
        <b>Title</b>			
		</div>
		<div class="text-center col-md-2">
		<b>Data Start</b>	
		</div>
		<div class="text-center col-md-2">
		<b>Data End</b>	
		</div>
		<div class="text-center col-md-1">
		<b>Category</b>
		</div>
		<div class="text-center col-md-3">
			<b>Commands</b>
		</div>
	</div>	
	<hr>
	<% events.each do |event| %>
	
	<div class="row">

		<div class="col-md-2">
			<%= image_tag(event.image_url(:thumb).to_s, :class => "img-thumbnail img-responsive") %>
		</div>
		<div class="text-center col-md-2">
			<%= event.title %>
		</div>
		<div class="text-center col-md-2">
			<%= event.dt_start.strftime("%d of %B %R") %>
		</div>
		<div class="text-center col-md-2">
			<%= event.dt_end.strftime("%d of %B %R") %>
		</div>
		<div class="text-center col-md-1">
			<%= event.category.name %>
		</div>
		<div class="btn-group-vertical col-md-3">
			<%= link_to 'Show', event, :class => 'btn btn-primary' %>

			<%= link_to 'Edit', edit_event_path(event), :class => 'btn btn-primary' %>

			<%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
		</div>
	</div>
	<hr>

	<% end %>
	<% end %>

app/views/events/_list_events_tumbnail.html.erb
<% events.each do |event| %>
<div class="col-md-4">
 <div class="thumbnail">
  <div class="caption">
    <%= image_tag(event.image_url, :class => "img-rounded img-responsive") %>
    <h4 class="text-center">
      <%= event.title %>
    </h4>
    <p class="text-center">
      Start: 
      <%= event.dt_start.strftime("%R %d/%B")%>
    </p>
    <p>
      <%= link_to 'See details', event, class: 'btn btn-default btn-block' %>
    </p>
  </div>
</div>
</div>

<% end %>

app/views/events/_list_events_users.html.erb
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Imagem </th>
        <th>Title</th>
        <th>Descripiton</th>
        <th>Contact</th>
        <th>dt_start</th>
        <th>dt_end</th>
        <th>category</th>
        <th>Show</th>
        <th>Edit</th>
        <th>Destroy</th>
      </tr>
    </thead>

    <tbody>
      <% events.each do |event| %>
      <tr>
        <td><%= image_tag(event.image, :class => "img-thumbnail img-responsive") %></td>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.contact %></td>
        <td><%= event.dt_start %></td>
        <td><%= event.dt_end %></td>
        <td><%= event.category %></td>
        <td><%= link_to 'Show', event, :class => 'btn btn-default' %></td>
        <td><%= link_to 'Edit', edit_event_path(event), :class => 'btn btn-default' %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>

app/views/events/edit.html.erb
<div class="page-header">
	<%= link_to events_path, class: 'btn btn-default' do %>
	<span class="glyphicon glyphicon-list-alt"></span>
	Back
	<% end %>
	<%= link_to @event, class: 'btn btn-primary' do %>
	<span class="glyphicon glyphicon-info-sign"></span>
	Show
	<% end %>

	<h1>Editing event</h1>
</div>

<%= render 'form' %>

app/views/events/index.html.erb
<div class="container">
  <div class="jumbotron fundo-com-gif">
    <h1>CulturaWeb</h1> 
    <p>Encontre os melhores eventos perto de você.</p>
  </div>

  <div class="page-header">

  </div>
  <div class="col-md-10">
   <%= render :partial => "events/list_events", locals: { events: @events }%>
 </div>
 <div class="col-md-2">
  <h3 class="text-center">Filters </h3>
  <div class="list-group">
    <%= link_to "Recent", events_path, class: "list-group-item list-group-item-action" %>
    <%= link_to "Today", events_path(time: "Today"), class: "list-group-item list-group-item-action" %>
    <%= link_to "This Week", events_path, class: "list-group-item list-group-item-action" %>
    <%= link_to "This Month", events_path, class: "list-group-item list-group-item-action" %>
  </br>
  <div class="dropdown">
    <button class="btn btn-default dropdown-toggle btn-block" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      Categories
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
      <li><a href="#">Music</a></li>
      <li><a href="#">Theather</a></li>
      <li><a href="#">Cinema</a></li>
      <li><a href="#">Congress</a></li>
    </ul>
  </div>
</div>
</div>

app/views/events/new.html.erb
<div class="page-header">
	<%= link_to events_path, class: 'btn btn-default' do %>
	<span class="glyphicon glyphicon-list-alt"></span>
	Back
	<% end %>
	<h1>New event</h1>
</div>

<%= render 'form' %>

app/views/events/show.html.erb
    <div class="page-header">
    <% if user_signed_in? %>
    <% if @event.company_id == current_user.company_id%>
      <%= link_to edit_event_path(@event), class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-pencil"></span>
      Edit
      <% end %>
    <% end %>
      <% if Subscribe.find_by(event_id: @event, user_id: current_user).nil? %>
      <%#= @event.has_subscribe?(@event, current_user) %>
          <%= link_to event_subscribe_path(@event), class: 'btn btn-success' do %>
          <span class="glyphicon glyphicon-pencil"></span>
          Subscribe
          <% end %>
      <% else %>
          <%= link_to event_unsubscribe_path(@event), class: 'btn btn-warning' do %>
          <span class="glyphicon glyphicon-pencil"></span>
          Unubscribe
          <% end %>
      <% end %>
    <% end %>
      
      <h1><%= @event.title%></h1>
    </div>

    <div class="well col-md-10 col-md-offset-1">

      <%= image_tag(@event.image_url.to_s, class:"img-responsive") %>
      <br/>
    </div>

    <div class="col-md-7 col-md-offset-1">
      <h2>Description:</h2>
      <dd><%= @event.description %></dd>
    </div>

    <div class="well col-md-3">
      <dt>Imagem:</dt>

      <dd><%= image_tag(google_map(center: @event.address.full_address), class:"img-responsive") %></dd>
      <%#=image_tag google_map(center: @event.address.full_address)%>
        <b>Address:</b><br/><%= @event.address.street %><br/><br/>
        <b>Company: </b><br/> <%= @event.company.name %><br/><br/>
        <b>Contact: </b><br/> <%= @event.contact %><br/><br/>
        <b>Category:</b><br/> <%= @event.category.name %><br/><br/>
        <b>Dt start:</b><br/> <%= @event.dt_start.strftime("%a, %d of %b %R") %><br/><br/>
        <b>Dt end:</b><br/> <%= @event.dt_end.strftime("%a, %d of %b %R")  %><br/><br/>
        <b>Price:</b><br/><br/>
        <table class="table table-striped table-hover">
          <% @prices.each do |p| %>
          <tr>
            <td>
              <strong><%= p.title %></strong> 
            </td>
            <td>
              <%= p.price %>
            </td>
          </tr>
          <% end %>
        </table>
      </h4>
    </div>

    <div class="col-md-10 col-md-offset-1">
       <%= render :partial => "events/list_events_tumbnail", locals: { events: @nearEvents }%>