config/routes.rb
Rails.application.routes.draw do
	resources :addresses
	resources :prices
	resources :events
	resources :companies
	resources :addresses

	devise_for :users, :controllers => { 
		:invitations => 'users/invitations'
	}

	resources :users, only: [:index, :destroy] 
	
	get "/users/:id/inviteUser" => "users#invite_User", :as => :invite_User

	resources :events, only: [:create] do
		get :subscribe
	end

	resources :events, only: [:destroy] do
		get :unsubscribe
	end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "events#index"
end

app/models/company.rb
class Company < ApplicationRecord
	#relaçoes
	has_many :users
	belongs_to :address, required: false

	#validaçoes
	validates :name, presence:true, length: { in: 2..50 }
 	validates :cnpj, :cnpj => true, uniqueness: true, :allow_blank => true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  load_and_authorize_resource
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies/1
  # GET /companies/1.json
  def show
   @events = Event.all.where(company_id: current_user.company_id)
   @companyUsers = User.all_users(current_user.company_id, current_user.id)
 end

  # GET /companies/new
  def new
    @company = Company.new
    @address = Address.new
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
    @address = Address.find_by_id(@company.address_id)
  end

  # POST /companies
  # POST /companies.json
  def create

    @address = Address.new(address_params)
    @company = Company.new(company_params)

    respond_to do |format|
      if @address.save
        @company.address_id = @address.id
        if @company.save
          if current_user.update(profile: 3, company_id: @company.id)
            format.html { redirect_to @company, notice: 'Company was successfully created.' }
            format.json { render :show, status: :created, location: @company }
          else
            format.html { render :new }
            format.json { render json: current_user.errors, status: :unprocessable_entity }
          end  
        else
         format.html { render :new }
         format.json { render json: @company.errors, status: :unprocessable_entity }
       end
     else
      format.html { render :new }
      format.json { render json: @address.errors, status: :unprocessable_entity }
    end
  end
end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update

    respond_to do |format|
      if @company.update(company_params)
        if @company.address.update(address_params)
          format.html { redirect_to @company, notice: 'Company was successfully updated.' }
          format.json { render :show, status: :ok, location: @company }
        else
         format.html { render :edit }
         format.json { render json: @company.errors, status: :unprocessable_entity }
       end
     else
      format.html { render :edit }
      format.json { render json: @company.errors, status: :unprocessable_entity }
    end
  end
end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    User.where(company_id: @company.id).update_all(profile: 1)
    @company.destroy
    current_user.update(profile: 1)
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    def set_address
      @address = Address.find(params[:id]) || Address.new
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:id, :name, :cnpj, :address_id, 
        address: [:street, :city, :zip, :state] )
    end

    def address_params
      params.require(:address).permit(:street, :city, :zip, :state)
    end
  end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company, html: { class: "form-horizontal col-md-6", role: "form" }) do |f| %>
<% if @company.errors.any? %>
<div class="alert alert-danger alert-dismissable" role="alert">
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  <h4><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h4>

  <ul>
    <% @company.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>


<div class="form-group">  
  <%= f.label :name, class: "col-md-2 control-label" %> 
  <div class="col-sm-12">
    <%= f.text_field :name, class: "form-control", placeholder: "Company name"%>
  </div>
</div>

<div class="form-group">
  <%= f.label :cnpj, class: "col-md-2 control-label" %>
  <div class="col-sm-12">
    <%= f.text_field :cnpj, class: "form-control",placeholder: "00.000.000/0000-00", :data => {:mask => "00.000.000/0000-00" }%>
  </div>
</div>

<%= f.hidden_field :id, class:"form-control"%>

<%= render :partial => "addresses/form"%>

<!--
<div class="form-group col-md-3 col-md-offset-3">
    <%= f.submit class: "btn btn-success" %>
</div>
-->
<% end %>

app/views/companies/edit.html.erb
<div class="page-header">
  <%= link_to @company, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing company</h1>
</div>
<div class="col-md-offset-4">
	<%= render 'form' %>
</div>

app/views/companies/index.html.erb
<div class="page-header">
  <%= link_to new_company_path, class: 'btn btn-primary' do %>
  <span class="glyphicon glyphicon-plus"></span>
  New Company
  <% end %>
  <h1>Listing companies</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Cnpj</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @companies.each do |company| %>
      <tr>
       <td><%= company.name %></td>
       <td><%= company.address %></td>
       <td><%= company.cnpj %></td>
       <td><%= link_to 'Show', company, :class => 'btn btn-default' %></td>
       <td><%= link_to 'Edit', edit_company_path(company), :class => 'btn btn-default' %></td>
       <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
       <% end %>
     </tr>
   </tbody>
 </table>

 <div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Descripiton</th>
        <th>Contact</th>
        <th>dt_start</th>
        <th>dt_end</th>
        <th>category</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
      <tr>
       <td><%= event.title %></td>
       <td><%= event.description %></td>
       <td><%= event.contact %></td>
       <td><%= event.dt_start %></td>
       <td><%= event.dt_end %></td>
       <td><%= event.category %></td>
       <td><%= link_to 'Show', event, :class => 'btn btn-default' %></td>
       <td><%= link_to 'Edit', edit_event_path(event), :class => 'btn btn-default' %></td>
       <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
       <% end %>
     </tr>
   </tbody>
 </table>
</div>

app/views/companies/new.html.erb
<div class="page-header">
	<h1>New company</h1>
</div>

	<%= render 'form' %>

app/views/companies/show.html.erb
<div class="page-header">
  <% if current_user.profile > 2 %>
  <%= link_to company_path(@company), method: :DELETE, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
  <span class="glyphicon glyphicon-list-alt"></span>
  Deletar Company
  <% end %>
  <%= link_to edit_company_path(@company), class: 'btn btn-primary' do %>
  <span class="glyphicon glyphicon-pencil"></span>
  Edit Company
  <% end %>
  <%= link_to new_user_invitation_path, remote: true, class: 'btn btn-primary' do %>
  <span class="glyphicon glyphicon-list-alt"></span>
  Invite new user
  <% end %>
  <% end %>
  <%= link_to new_event_path, class: 'btn btn-success' do %>
  <span class="glyphicon glyphicon-list-alt"></span>
  New Event
  <% end %>
  <h1>Show company</h1>
</div>

<dl class="row row-horizontal col-md-2">
  <dt>Name:</dt>
  <dd><%= @company.name %></dd>

  <dt>Address:</dt>
  <%if @company.cnpj.nil? %>
  <dt>Cnpj:</dt>
  <dd><%= @company.cnpj %></dd>
  <% end %>  
  <dd><%= @company.address.street %></dd>
  <br/>
  <dd><%= image_tag(google_map(center: @company.address.full_address), class:"img-responsive") %></dd>
</dl>

<div class="col-md-10">
  <% if current_user.profile == 3%>
  <%= tabs do |c| %>
    
  <% c.tab 'Eventos' do %>
  <div class="well">
  <div>
    <%= render :partial => "events/list_events_manage", locals: { events: @events }%>
  </div>
  </div>
  <% end %>
  <% c.tab 'Usuarios' do %>
  <div>
    <div class="well">  
    <%= render :partial => "users/list_company_users", locals: { users: @companyUsers }%>
  </div>
  </div>
  <% end %>
  <% end %>
</div>

<% else %>
<%= render :partial => "events/list_events_manage", locals: { events: @events }%>

<% end %>