config/routes.rb
Rails.application.routes.draw do
	resources :addresses
	resources :prices
	resources :events
	resources :companies
	resources :addresses

	devise_for :users, :controllers => { 
		:invitations => 'users/invitations'
	}

	resources :users, only: [:index, :destroy] 
	
	get "/users/:id/inviteUser" => "users#invite_User", :as => :invite_User

	resources :events, only: [:create] do
		get :subscribe
	end

	resources :events, only: [:destroy] do
		get :unsubscribe
	end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "events#index"
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :event
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show, :edit, :update, :destroy]
  before_action :set_event
  # GET /prices
  # GET /prices.json
  def index
    @prices = Price.all
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
  end

  # GET /prices/new
  def new
    @price = Price.new
    @price.event_id = params[:event_id]
  end

  # GET /prices/1/edit
  def edit
  end

  # POST /prices
  # POST /prices.json
  def create
    @price = Price.new(price_params)
    if @price.title.blank?
      @price.title = "Free"
    end
    respond_to do |format|
      if @price.save
       format.html { redirect_to edit_event_path(Event.find(price_params[:event_id])), notice: 'Price was successfully created.' }
       format.json { render :edit, status: :created, location: event }
     else
      format.html { render :show }
      format.json { render json: @price.errors, status: :unprocessable_entity }
    end
  end
end

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json
  def update
    respond_to do |format|
binding.pry
      if @price.update(price_params)
        format.html { redirect_to edit_event_path(Event.find(price_params[:event_id])), notice: 'Price was successfully updated.' }
        format.json { render :edit, status: :ok, location: @price }
      else
        format.html { render :edit }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    binding.pry
    event = Event.find(@price.event_id)
    @price.destroy
    respond_to do |format|
      format.html { redirect_to edit_event_path(event), notice: 'Price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find_by(params[:event_id]) || Price.new
    end

    def set_event
      @event = Event.find_by_id(params[:event_id]) 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_params
      params.require(:price).permit(:title, :price, :event_id)
    end
  end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/_edit.html.erb
<div class="page-header">
  <%= link_to prices_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @price, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing price</h1>
</div>

<%= render 'form' %>

app/views/prices/_form.html.erb
<div id="contact-modal" class="modal fade ">
  <div class="modal-dialog">
    <div class="modal-content">

      <%= form_for(@price, html: { class: "form-horizontal", role: "form" }) do |f| %>
      <div class="modal-body">
        <% if @price.errors.any? %>
        <div class="alert alert-danger alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4><%= pluralize(@price.errors.count, "error") %> prohibited this price from being saved:</h4>

          <ul>
            <% @price.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
        <% end %>

        <div class="form-group">
          <%= f.label :title, class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :title, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :price, class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :price, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-10">
            <%= f.hidden_field :event_id, class: "form-control" %>
          </div>
        </div>
        <div class="modal-footer">
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <%= f.submit class: "btn btn-primary" %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/prices/_index.html.erb
<div class="page-header">
  <%= link_to new_price_path(event_id: @event.id), remote: true, class: 'btn btn-primary' do %>
  <span class="glyphicon glyphicon-list-alt"></span>
  New Price
  <% end %>
  <h1>Listing prices</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Price</th>
        
        <th class="col-md-2"> Commands</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <% prices.each do | price | %>
        <td class="text-center"><%= price.title %></td>
        <td class="text-center"><%= price.price %></td>
        <td class="btn-group-vertical col-md-2">
          <%= link_to 'Edit', edit_price_path(price),  remote: true, class:"btn btn-warning" %>
          <%= link_to 'Destroy', price, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
          
        </td>
        <tr>
          <% end %>
        </tbody>
      </table>
    </div>

app/views/prices/_new.html.erb
<div class="page-header">
  <%= link_to prices_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New price</h1>
</div>
  

<%= render 'form' %>

app/views/prices/edit.js.erb
$('<%= j render "edit" %>').modal();

app/views/prices/new.js.erb
$('<%= j render "new" %>').modal();