config/routes.rb
Rails.application.routes.draw do
	resources :addresses
	resources :prices
	resources :events
	resources :companies
	resources :addresses

	devise_for :users, :controllers => { 
		:invitations => 'users/invitations'
	}

	resources :users, only: [:index, :destroy] 
	
	get "/users/:id/inviteUser" => "users#invite_User", :as => :invite_User

	resources :events, only: [:create] do
		get :subscribe
	end

	resources :events, only: [:destroy] do
		get :unsubscribe
	end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "events#index"
end

app/views/layouts/_navbar_dropdown_user.html.erb
<p class="navbar-text"> Logged in as <strong><%= current_user.email %></strong></p>
<li><%= link_to "My Calendar", users_path, :class => "navbar-link"%></li>

<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" 
  aria-expanded="false">Menu<span class="caret"></span>
</a>
<ul class="dropdown-menu">
    <% if current_user.profile == 1 %>
    <li> <%= link_to 'New Company', new_company_path, :class => 'dropdown-item' %> </li>
    <% end %>
    <% if current_user.profile > 1 %>
    <li> <%= link_to 'New Event',  new_event_path, :class => 'dropdown-item' %></li>
    <!-- Dropdown Menu-->
    <li> <%= link_to 'Show Company', company_path(current_user.company_id), :class => 'dropdown-item' %> </li> 
    <% end %>
    <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'dropdown-item' %> </li> 
    <li role="separator" class="divider"></li>
    <li><%= link_to "Logout", destroy_user_session_path, :method => 'get', :class => 'dropdown-item'  %></li>
</ul>

app/views/layouts/_search_navbar.html.erb
<%= form_tag events_path, method: :get, class: '' do %>
 <div class="row">
  <div class="col-lg-10">
    <div class="input-group">
      <%= text_field_tag :q, @search_query, placeholder: 'Event Name', class:'form-control' %>
      <span class="input-group-btn">
        <!--<button class="btn btn-default" type="button">Search</button>-->
      	<%= submit_tag "Search", class: "btn btn-default" %>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->
<% end %>
<!--
<%= form_tag events_path, method: :get, class: 'input-group' do %>
<%= text_field_tag :q, @search_query, placeholder: 'Search', class:'form-control' %>
<span class="input-group-btn">
  <%= submit_tag 'Search', class:'btn btn-default'%>
</span>
<% end %>
-->

app/views/layouts/application.html.erb
<html>
<!DOCTYPE html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>CulturaWeb</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
    <![endif]-->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <%= csrf_meta_tags %>

  </head>
  
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top navbar-colapse cor-principal" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Cultura Web", root_path, class: "navbar-brand" %>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-menu-expand" aria-expanded="false">Expandir</button>
        </div>
        <div class="collapse navbar-collapse" id="navbar-menu-expand">
        <div class="col-md-4">
            <form class="navbar-form navbar-left" role="search">
              <%= render 'layouts/search_navbar'%>
            </form>
          </div>
          <div class="navbar-right">
            <ul class="nav navbar-nav">
              <% if user_signed_in? %>
              <%= render 'layouts/navbar_dropdown_user' %>       
              <% else %>
              <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
              <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> </li>
              <% end %>
            </ul>
          </div>
        </nav>
      </div>
    </div>
    <div class="container">
      <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <%= msg %>
      <% end %>
      <% end %>

      <%= yield %>

    </div>
    <br/><br/><br/><br/><br/><br/><br/><br/>
  </body>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </html>